### ISSUE TITLE
don't be cheaters!

### ISSUE THREAD

**Issue by JeffVu-1** [Kinuzo/ardoras#30]
don't be cheaters

**Comment by alienjawa25** [comment]
try to right click trigger, or delete the string, it will automatically magneting

**Comment by FadyAshraf242** [comment]
i need tutotrial video
can anyone help me?

**Comment by FadyAshraf242** [comment]
> 

i need tutotrial video

**Comment by alienjawa25** [comment]
dm my discord Mellv1n#3270

**Comment by LukiPukiNom** [comment]
> 

I need help too:  luccass#2535
